use std::net::IpAddr;
use std::sync::Arc;

use crate::cel::Expression;
use crate::store::HasExpressions;
use crate::*;

#[apply(schema!)]
#[cfg_attr(feature = "schema", schemars(rename = "LoadBalancingPolicy"))]
pub struct Policy {
	/// Consistently hash requests to backend endpoints based on a request property, providing
	/// best-effort session affinity: requests with the same key are routed to the same endpoint
	/// as long as the endpoint set is stable.
	pub consistent_hash: ConsistentHash,
}

#[apply(schema!)]
#[cfg_attr(feature = "schema", schemars(rename = "ConsistentHash"))]
pub struct ConsistentHash {
	#[serde(flatten)]
	pub hash_on: HashOn,
}

/// The request property used as the hash key. Exactly one may be set.
#[apply(schema!)]
pub enum HashOn {
	/// Hash the value of a request header. Requests without the header are not hashed.
	Header(Strng),
	/// Hash the value of an HTTP cookie. Requests without the cookie are not hashed;
	/// the cookie is never generated by the gateway.
	Cookie(CookieHash),
	/// Hash the source IP address of the client connection.
	SourceIp(bool),
	/// Hash the value of a query parameter. Requests without the parameter are not hashed.
	QueryParam(Strng),
	/// Hash the result of a CEL expression evaluated against the request,
	/// e.g. `request.headers["x-user"]`. Requests where evaluation fails are not hashed.
	Expression(Arc<Expression>),
}

#[apply(schema!)]
pub struct CookieHash {
	/// Name of the cookie.
	pub name: Strng,
}

impl HasExpressions for Policy {
	fn expressions(&self) -> impl Iterator<Item = &Expression> {
		match &self.consistent_hash.hash_on {
			HashOn::Expression(e) => Some(e.as_ref()),
			_ => None,
		}
		.into_iter()
	}
}

impl Policy {
	/// Computes the consistent-hash key for a request, or None when the configured key is
	/// absent (callers fall back to the default load balancing algorithm).
	pub fn request_hash(&self, req: &http::Request, source_ip: Option<IpAddr>) -> Option<u64> {
		match &self.consistent_hash.hash_on {
			HashOn::Header(name) => {
				let v = req.headers().get(name.as_str())?;
				Some(hash(v.as_bytes()))
			},
			HashOn::Cookie(c) => {
				for header in req.headers().get_all(::http::header::COOKIE) {
					let Ok(header) = header.to_str() else {
						continue;
					};
					for ck in cookie::Cookie::split_parse(header).flatten() {
						if ck.name() == c.name.as_str() {
							return Some(hash(ck.value().as_bytes()));
						}
					}
				}
				None
			},
			HashOn::SourceIp(enabled) => {
				if !enabled {
					return None;
				}
				Some(hash(source_ip?.to_string().as_bytes()))
			},
			HashOn::QueryParam(name) => {
				let query = req.uri().query()?;
				url::form_urlencoded::parse(query.as_bytes())
					.find(|(k, _)| k == name.as_str())
					.map(|(_, v)| hash(v.as_bytes()))
			},
			HashOn::Expression(expr) => {
				let exec = cel::Executor::new_request(req);
				let v = exec.eval(expr.as_ref()).ok()?.json().ok()?;
				match v {
					serde_json::Value::Null => None,
					serde_json::Value::String(s) => Some(hash(s.as_bytes())),
					other => Some(hash(other.to_string().as_bytes())),
				}
			},
		}
	}
}

/// Request-key and ring-point hash. xxhash64 with zero seed, matching Envoy's default
/// `XX_HASH` ring hash function; must stay stable so mappings agree across instances and restarts.
pub fn hash(bytes: &[u8]) -> u64 {
	twox_hash::XxHash64::oneshot(0, bytes)
}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::http::tests_common::request;

	fn parse(v: serde_json::Value) -> Policy {
		serde_json::from_value(v).expect("policy must parse")
	}

	#[test]
	fn parses_flat_hash_key_variants() {
		let pol = parse(serde_json::json!({"consistentHash": {"header": "x-session-id"}}));
		assert!(matches!(
			&pol.consistent_hash.hash_on,
			HashOn::Header(h) if h == "x-session-id"
		));
		let pol = parse(serde_json::json!({"consistentHash": {"cookie": {"name": "sid"}}}));
		assert!(matches!(
			&pol.consistent_hash.hash_on,
			HashOn::Cookie(c) if c.name == "sid"
		));
		let pol = parse(serde_json::json!({"consistentHash": {"sourceIp": true}}));
		assert!(matches!(
			&pol.consistent_hash.hash_on,
			HashOn::SourceIp(true)
		));
		let pol = parse(serde_json::json!({"consistentHash": {"queryParam": "user"}}));
		assert!(matches!(
			&pol.consistent_hash.hash_on,
			HashOn::QueryParam(q) if q == "user"
		));
		let pol = parse(serde_json::json!({"consistentHash": {"expression": "request.method"}}));
		assert!(matches!(
			&pol.consistent_hash.hash_on,
			HashOn::Expression(_)
		));
	}

	#[test]
	fn rejects_multiple_or_missing_hash_keys() {
		serde_json::from_value::<Policy>(
			serde_json::json!({"consistentHash": {"header": "a", "queryParam": "b"}}),
		)
		.expect_err("two hash keys must be rejected");
		serde_json::from_value::<Policy>(serde_json::json!({"consistentHash": {}}))
			.expect_err("a hash key is required");
	}

	#[test]
	fn hashes_header_value() {
		let pol = parse(serde_json::json!({"consistentHash": {"header": "x-user"}}));
		let req = request(
			"http://example.com/",
			::http::Method::GET,
			&[("x-user", "alice")],
		);
		assert_eq!(pol.request_hash(&req, None), Some(hash(b"alice")));
		let req = request("http://example.com/", ::http::Method::GET, &[]);
		assert_eq!(pol.request_hash(&req, None), None);
	}

	#[test]
	fn hashes_cookie_value() {
		let pol = parse(serde_json::json!({"consistentHash": {"cookie": {"name": "sid"}}}));
		let req = request(
			"http://example.com/",
			::http::Method::GET,
			&[("cookie", "other=1; sid=abc")],
		);
		assert_eq!(pol.request_hash(&req, None), Some(hash(b"abc")));
		let req = request(
			"http://example.com/",
			::http::Method::GET,
			&[("cookie", "other=1")],
		);
		assert_eq!(pol.request_hash(&req, None), None);
	}

	#[test]
	fn hashes_source_ip() {
		let pol = parse(serde_json::json!({"consistentHash": {"sourceIp": true}}));
		let req = request("http://example.com/", ::http::Method::GET, &[]);
		let ip: IpAddr = "10.1.2.3".parse().unwrap();
		assert_eq!(pol.request_hash(&req, Some(ip)), Some(hash(b"10.1.2.3")));
		assert_eq!(pol.request_hash(&req, None), None);

		let pol = parse(serde_json::json!({"consistentHash": {"sourceIp": false}}));
		assert_eq!(pol.request_hash(&req, Some(ip)), None);
	}

	#[test]
	fn hashes_query_param() {
		let pol = parse(serde_json::json!({"consistentHash": {"queryParam": "user"}}));
		let req = request(
			"http://example.com/path?a=1&user=bob",
			::http::Method::GET,
			&[],
		);
		assert_eq!(pol.request_hash(&req, None), Some(hash(b"bob")));
		let req = request("http://example.com/path?a=1", ::http::Method::GET, &[]);
		assert_eq!(pol.request_hash(&req, None), None);
	}

	#[test]
	fn hashes_expression_result() {
		let pol = parse(serde_json::json!({"consistentHash": {"expression": "request.method"}}));
		let req = request("http://example.com/", ::http::Method::GET, &[]);
		assert_eq!(pol.request_hash(&req, None), Some(hash(b"GET")));

		// Failing evaluation yields no hash rather than an error.
		let pol =
			parse(serde_json::json!({"consistentHash": {"expression": "request.headers[\"absent\"]"}}));
		assert_eq!(pol.request_hash(&req, None), None);
	}
}
